### ISSUE TITLE
Menu does not display

### ISSUE THREAD

**Issue by brycie** [Luminous-Roleplay/LRP_Stable#1]
Script loads show no errors, However does not function. When prompted to press E to open stable, The camera moves but no menu opens, This also forces me to close the game via task manager as I can no longer exit after interacting with the stable.

**Comment by CrazyHobo420** [comment]
I'm having the same issue as brycie.

**Comment by klandestino7** [comment]
I just fixed the problems

**Comment by brycie** [comment]
Issue not solved my end Still does not show the menu, allows you to keep pressing alt, this results in the camera moving, nothing else. You are also then locked and unable to exit from the stable. I still have to force close redem via taskmanager. Still no errors shown in console to help :/

**Comment by CrazyHobo420** [comment]
Same problem still happening.

**Comment by 1123581** [comment]
I fixed the issue for me buy changing the fxmanifest under files for instance where 'html/*' i replaced the '*' with the actual file names, so 'html/index.html' and 'html/jquery.js'... i think thats all i did... its all a blur
